"""criacao_inicial

Revision ID: b5d1ea49de14
Revises: 
Create Date: 2026-07-13 19:54:44.551890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d1ea49de14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_base', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('sazonal', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_table('promocoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo_desconto', sa.String(length=20), nullable=False),
    sa.Column('valor_desconto', sa.Float(), nullable=False),
    sa.Column('codigo_cupom', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocoes_codigo_cupom'), 'promocoes', ['codigo_cupom'], unique=True)
    op.create_index(op.f('ix_promocoes_id'), 'promocoes', ['id'], unique=False)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('logradouro', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_id'), 'unidades', ['id'], unique=False)
    op.create_table('cardapio_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('preco_especifico', sa.Float(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'produto_id', name='uq_cardapio_unidade_produto')
    )
    op.create_index(op.f('ix_cardapio_unidade_id'), 'cardapio_unidade', ['id'], unique=False)
    op.create_index(op.f('ix_cardapio_unidade_produto_id'), 'cardapio_unidade', ['produto_id'], unique=False)
    op.create_index(op.f('ix_cardapio_unidade_unidade_id'), 'cardapio_unidade', ['unidade_id'], unique=False)
    op.create_table('configuracoes_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('horario_abertura', sa.Time(), nullable=True),
    sa.Column('horario_fechamento', sa.Time(), nullable=True),
    sa.Column('tipo_cozinha', sa.String(length=20), nullable=False),
    sa.Column('dias_funcionamento', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id')
    )
    op.create_index(op.f('ix_configuracoes_unidade_id'), 'configuracoes_unidade', ['id'], unique=False)
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('qtd_minima', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'produto_id', name='uq_estoque_unidade_produto')
    )
    op.create_index(op.f('ix_estoque_id'), 'estoque', ['id'], unique=False)
    op.create_index(op.f('ix_estoque_produto_id'), 'estoque', ['produto_id'], unique=False)
    op.create_index(op.f('ix_estoque_unidade_id'), 'estoque', ['unidade_id'], unique=False)
    op.create_table('promocao_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocao_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promocao_id'], ['promocoes.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocao_id', 'unidade_id', name='uq_promocao_unidade')
    )
    op.create_index(op.f('ix_promocao_unidade_id'), 'promocao_unidade', ['id'], unique=False)
    op.create_index(op.f('ix_promocao_unidade_promocao_id'), 'promocao_unidade', ['promocao_id'], unique=False)
    op.create_index(op.f('ix_promocao_unidade_unidade_id'), 'promocao_unidade', ['unidade_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('consentimentos_lgpd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_consentimento', sa.String(length=50), nullable=False),
    sa.Column('consentiu', sa.Boolean(), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentimentos_lgpd_id'), 'consentimentos_lgpd', ['id'], unique=False)
    op.create_index(op.f('ix_consentimentos_lgpd_usuario_id'), 'consentimentos_lgpd', ['usuario_id'], unique=False)
    op.create_table('fidelidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pontos_acumulados', sa.Integer(), nullable=False),
    sa.Column('pontos_resgatados', sa.Integer(), nullable=False),
    sa.Column('pontos_disponiveis', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    op.create_index(op.f('ix_fidelidade_id'), 'fidelidade', ['id'], unique=False)
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('dados_anteriores', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_id'), 'logs_auditoria', ['id'], unique=False)
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_estoque_estoque_id'), 'movimentacoes_estoque', ['estoque_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_id'), 'movimentacoes_estoque', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=True),
    sa.Column('cancelado_por', sa.Integer(), nullable=True),
    sa.Column('canal_pedido', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atendente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cancelado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_cliente_id'), 'pedidos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_unidade_id'), 'pedidos', ['unidade_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('historico_fidelidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fidelidade_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fidelidade_id'], ['fidelidade.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_fidelidade_fidelidade_id'), 'historico_fidelidade', ['fidelidade_id'], unique=False)
    op.create_index(op.f('ix_historico_fidelidade_id'), 'historico_fidelidade', ['id'], unique=False)
    op.create_index(op.f('ix_historico_fidelidade_pedido_id'), 'historico_fidelidade', ['pedido_id'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_pedido_id'), 'itens_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_produto_id'), 'itens_pedido', ['produto_id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('ref_externa', sa.String(length=100), nullable=True),
    sa.Column('payload_retorno', sa.JSON(), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.create_index(op.f('ix_pagamentos_pedido_id'), 'pagamentos', ['pedido_id'], unique=True)
    op.create_table('pedido_promocao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('promocao_id', sa.Integer(), nullable=False),
    sa.Column('valor_desconto_aplicado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['promocao_id'], ['promocoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_promocao_id'), 'pedido_promocao', ['id'], unique=False)
    op.create_index(op.f('ix_pedido_promocao_pedido_id'), 'pedido_promocao', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_promocao_promocao_id'), 'pedido_promocao', ['promocao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_promocao_promocao_id'), table_name='pedido_promocao')
    op.drop_index(op.f('ix_pedido_promocao_pedido_id'), table_name='pedido_promocao')
    op.drop_index(op.f('ix_pedido_promocao_id'), table_name='pedido_promocao')
    op.drop_table('pedido_promocao')
    op.drop_index(op.f('ix_pagamentos_pedido_id'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_itens_pedido_produto_id'), table_name='itens_pedido')
    op.drop_index(op.f('ix_itens_pedido_pedido_id'), table_name='itens_pedido')
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_historico_fidelidade_pedido_id'), table_name='historico_fidelidade')
    op.drop_index(op.f('ix_historico_fidelidade_id'), table_name='historico_fidelidade')
    op.drop_index(op.f('ix_historico_fidelidade_fidelidade_id'), table_name='historico_fidelidade')
    op.drop_table('historico_fidelidade')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pedidos_unidade_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_movimentacoes_estoque_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_estoque_id'), table_name='movimentacoes_estoque')
    op.drop_table('movimentacoes_estoque')
    op.drop_index(op.f('ix_logs_auditoria_id'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    op.drop_index(op.f('ix_fidelidade_id'), table_name='fidelidade')
    op.drop_table('fidelidade')
    op.drop_index(op.f('ix_consentimentos_lgpd_usuario_id'), table_name='consentimentos_lgpd')
    op.drop_index(op.f('ix_consentimentos_lgpd_id'), table_name='consentimentos_lgpd')
    op.drop_table('consentimentos_lgpd')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_promocao_unidade_unidade_id'), table_name='promocao_unidade')
    op.drop_index(op.f('ix_promocao_unidade_promocao_id'), table_name='promocao_unidade')
    op.drop_index(op.f('ix_promocao_unidade_id'), table_name='promocao_unidade')
    op.drop_table('promocao_unidade')
    op.drop_index(op.f('ix_estoque_unidade_id'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_produto_id'), table_name='estoque')
    op.drop_index(op.f('ix_estoque_id'), table_name='estoque')
    op.drop_table('estoque')
    op.drop_index(op.f('ix_configuracoes_unidade_id'), table_name='configuracoes_unidade')
    op.drop_table('configuracoes_unidade')
    op.drop_index(op.f('ix_cardapio_unidade_unidade_id'), table_name='cardapio_unidade')
    op.drop_index(op.f('ix_cardapio_unidade_produto_id'), table_name='cardapio_unidade')
    op.drop_index(op.f('ix_cardapio_unidade_id'), table_name='cardapio_unidade')
    op.drop_table('cardapio_unidade')
    op.drop_index(op.f('ix_unidades_id'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_promocoes_id'), table_name='promocoes')
    op.drop_index(op.f('ix_promocoes_codigo_cupom'), table_name='promocoes')
    op.drop_table('promocoes')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
