# Importa todos os models para que o Alembic detecte as tabelas automaticamente
from app.domain.models.unidade import Unidade
from app.domain.models.produto import Produto
from app.domain.models.promocao import Promocao
from app.domain.models.usuario import Usuario
from app.domain.models.configuracao_unidade import ConfiguracaoUnidade
from app.domain.models.cardapio_unidade import CardapioUnidade
from app.domain.models.estoque import Estoque
from app.domain.models.promocao_unidade import PromocaoUnidade
from app.domain.models.refresh_token import RefreshToken
from app.domain.models.fidelidade import Fidelidade
from app.domain.models.consentimento_lgpd import ConsentimentoLGPD
from app.domain.models.log_auditoria import LogAuditoria
from app.domain.models.movimentacao_estoque import MovimentacaoEstoque
from app.domain.models.pedido import Pedido
from app.domain.models.item_pedido import ItemPedido
from app.domain.models.pagamento import Pagamento
from app.domain.models.historico_fidelidade import HistoricoFidelidade
from app.domain.models.pedido_promocao import PedidoPromocao
